### ISSUE TITLE
yolov7.onnx and bytetrack

### ISSUE THREAD

**Issue by JovanBosic** [Kazuhito00/ByteTrack-ONNX-Sample#1]
このリポジトリをありがとうございます。 yolov7.pthモデルをonnxモデルに変換したので、コードとバイトトラックアルゴリズムで試してみたいと思います。 やり方を教えてもらえますか？ いくつかの手順を実行しましたが、yolox_utils.pyの関数post_processに問題があります。 私はそのスクリプトを変更する必要があると思いますが、あなたのコメントがなければ、それは簡単な作業ではありません。 どんな提案でも多くのことを意味します！ 前もって感謝します！

**Comment by Kazuhito00** [comment]
以下のリポジトリを参考にpost_processを実装してはいかがでしょうか？
https://github.com/ibaiGorordo/ONNX-YOLOv7-Object-Detection

**Comment by JovanBosic** [comment]
どうもありがとうございます。 推論速度を改善する方法と、トラッカーのパラメーターを微調整してパフォーマーを後押しする方法について何か提案はありますか?

**Comment by JovanBosic** [comment]
ビデオでは、立っているだけの人が何人かいて、オブジェクト検出だけを行うと、検出器は 0.8 以上の信頼度でそれらをすべて検出しますが、追跡を実行すると、何らかの理由で ID が取得されず、検出されません。

**Comment by JovanBosic** [comment]
検出器は、トラッカーの内側と外側で同じように機能しないようです。

**Comment by JovanBosic** [comment]
![detect](https://user-images.githubusercontent.com/44612873/182164650-90be2b73-f22b-4790-af88-2c18dd2ffb1d.png)
![track](https://user-images.githubusercontent.com/44612873/182164668-9b5cc111-ac33-45a5-8cf1-0926acaa4bb9.png)

**Comment by JovanBosic** [comment]
私はそれを見つけた。 問題が bbox の形状に関するものであることを共有できてとても興奮しています。 if tlwh[2] * tlwh[3] > self.args.min_box_area and not vertical: というコード行に簡単にコメントを付けました。 ご協力ありがとうございました！
